//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carsharing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsharingEntities : DbContext
    {
        private static CarsharingEntities _context;
        public CarsharingEntities()
            : base("name=CarsharingEntities")
        {
        }
        public static CarsharingEntities GetContext()
        {
            if (_context == null) 
                _context = new CarsharingEntities();
            return _context;
            
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accidents> Accidents { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Fleet> Fleet { get; set; }
        public virtual DbSet<Maintenance_Events> Maintenance_Events { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariffs> Tariffs { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<Vehicle_Coordinates> Vehicle_Coordinates { get; set; }
    }
}
