//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиенты()
        {
            this.ДТП = new HashSet<ДТП>();
            this.Поездки = new HashSet<Поездки>();
        }
    
        public int ID_Клиента { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_Рождения { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
        public string Номер_ВУ { get; set; }
        public Nullable<System.DateTime> Дата_Выдачи_ВУ { get; set; }
        public string НомерСерия_Паспорта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДТП> ДТП { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поездки> Поездки { get; set; }
    }
}
