//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата
    {
        public int ID_Оплаты { get; set; }
        public Nullable<int> ID_Поездки { get; set; }
        public Nullable<System.DateTime> ДатаВремя { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Поездки Поездки { get; set; }
    }
}
