//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховые_Данные
    {
        public string ID_Страховки { get; set; }
        public Nullable<int> ID_Автомобиля { get; set; }
        public Nullable<System.DateTime> ДатаНачалаСтрахования { get; set; }
        public Nullable<System.DateTime> ДатаКонцаСтрахования { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
    }
}
